#!/usr/bin/env bash
# PreToolUse (Edit|Write|MultiEdit): refuse edits to generated or upstream-owned paths.
# Exit 2 = block; the message on stderr is shown to Claude.
set -euo pipefail
INPUT=$(cat)
FILE=$(printf '%s' "$INPUT" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("tool_input",{}).get("file_path") or d.get("tool_input",{}).get("path") or "")' 2>/dev/null || true)
[ -n "$FILE" ] || exit 0
ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
REL="${FILE#"$ROOT"/}"

deny() { echo "BLOCKED: $REL — $1" >&2; exit 2; }

case "$REL" in
  tool/src/main/AndroidManifest.xml)
    deny "never hand-write the manifest; the light-sdk plugin generates it from tool/lighttool.toml and rejects a hand-written one." ;;
  tool/src/main/assets/compendium/*|tool/src/main/assets/legal/*)
    deny "generated by the pipeline. Change pipeline/ (normalize/, legal.py, sources.lock.json) and run: python3 -m pipeline build" ;;
  fixtures/characters/*|fixtures/journal/*) ;;  # hand-written samples are editable
  fixtures/*.json)
    deny "golden fixtures are generated from pipeline/reference/. Fix the reference engine, then: python3 -m pipeline fixtures" ;;
  LICENSES/CC-BY-4.0.txt)
    deny "license text is fetched verbatim by the pipeline (SPDX copy); do not edit." ;;
  sdk/*|plugin/*|builder/*|lint-rules/*|settings.gradle.kts|build.gradle.kts|gradle/*)
    deny "upstream light-sdk files. Tools never patch the SDK locally — file an issue on lightphone/light-sdk, wait for a green light, then branch in the light-sdk fork (see light-workspace/docs/SYNCING.md)." ;;
  tool/src/main/java/*|*.java)
    deny "the plugin scan rejects .java sources in tool modules — write Kotlin." ;;
esac
exit 0
