plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.light.sdk)
}

android {
    compileSdk = rootProject.ext["compileSdk"] as Int

    signingConfigs {
        create("lightsdkDev") {
            storeFile = file("../sdk/keys/lightsdk-dev.jks")
            storePassword = "android"
            keyAlias = "lightsdk-dev"
            keyPassword = "android"
            enableV3Signing = true
            enableV4Signing = true
        }
    }

    defaultConfig {
        minSdk = rootProject.ext["minSdk"] as Int
        targetSdk = rootProject.ext["targetSdk"] as Int

        manifestPlaceholders["sdkVersion"] = property("sdkVersion") as String
    }

    // S16 About prints the version, the tool id and "5E compatible" (docs/UI-SPEC.md S16). The Light plugin
    // injects applicationId / versionCode / versionName into defaultConfig from lighttool.toml — and the
    // build script may not set them itself — so BuildConfig is the one reading of those three fields that
    // cannot drift from the toml the builder ships.
    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("lightsdkDev")
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"))
            signingConfig = signingConfigs.getByName("lightsdkDev")
        }
    }

    lint {
        warningsAsErrors = false
        error += "RestrictedApi"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(rootProject.ext["jvmTarget"] as String)
        targetCompatibility = JavaVersion.toVersion(rootProject.ext["jvmTarget"] as String)
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(rootProject.ext["jvmTarget"] as String))
    }
}

dependencies {
    implementation(project(":sdk:client"))
    // Room, DataStore, coroutines and lifecycle-viewmodel already reach us as `api` from :sdk:client; the keyboard
    // and Compose from :sdk:ui. Room and DataStore are restated because this tool depends on them directly
    // (00-ASSESSMENT.md). kotlinx-serialization-json is the only genuinely new dependency.
    ksp(libs.androidx.room.compiler)
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.kotlinx.serialization.json)
    testImplementation(libs.kotlin.test)
}

// Golden fixtures live at <repo>/fixtures (generated by pipeline/). JVM tests read them in place through
// -Dgrimoire.fixtures; declaring the directory as a task input re-runs the replays when the pipeline
// regenerates a file. No copy (nothing to drift) and no custom source-directory registration (the Light SDK plugin scan bans it).
// Light's builder never runs unit tests, so the directory's absence there is irrelevant.
// The compendium's armor table (assets/compendium/equipment.json) is an input of derived.json and
// events.json, so the bundled compendium is handed to the tests the same way (it ships in the module,
// hence never optional).
// The generated legal text (assets/legal/ATTRIBUTION.md, written by pipeline/legal.py) reaches the tests the
// same way: AboutViewModelTest asserts the CC-BY sentence and the modification notice survive the About
// screen, so a regenerated attribution must re-run that test.
val fixturesDir = rootProject.layout.projectDirectory.dir("fixtures")
val compendiumDir = layout.projectDirectory.dir("src/main/assets/compendium")
val legalDir = layout.projectDirectory.dir("src/main/assets/legal")
tasks.withType<Test>().configureEach {
    inputs.dir(fixturesDir).optional(true)   // absent on Light's builder, which never runs tests
    inputs.dir(compendiumDir)
    inputs.dir(legalDir)
    systemProperty("grimoire.fixtures", fixturesDir.asFile.absolutePath)
    systemProperty("grimoire.compendium", compendiumDir.asFile.absolutePath)
    systemProperty("grimoire.legal", legalDir.asFile.absolutePath)
}
