package dev.tyler.grimoire.ui.about

import android.view.KeyEvent
import androidx.lifecycle.viewModelScope
import com.thelightphone.sdk.LightViewModel
import com.thelightphone.sdk.SimpleLightScreen
import dev.tyler.grimoire.compendium.Block
import dev.tyler.grimoire.compendium.Markdown
import dev.tyler.grimoire.compendium.Span
import dev.tyler.grimoire.ui.keys.WheelEvent
import dev.tyler.grimoire.ui.keys.WheelHandler
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlin.coroutines.cancellation.CancellationException

/**
 * S16's view model: the bundled attribution and the four identity lines (docs/UI-SPEC.md S16).
 *
 * The CC-BY-4.0 attribution is a legal obligation, not copy: `assets/legal/ATTRIBUTION.md` is generated by
 * `pipeline/legal.py` and rendered **verbatim** here — the exact SRD 5.1 sentence plus the modification
 * notice CC-BY-4.0 §3(a)(1)(B) requires (docs/LICENSING.md). Nothing may be added beside it: no trademark
 * line, no Fan Content text, no second Wizards attribution. `AboutViewModelTest` reads the real asset and
 * asserts both sentences survive whatever this screen does to them.
 *
 * [readAsset] is a lambda, not the `SealedLightContext`, so the whole class runs on the JVM: the screen
 * passes `{ String(lightContext.readAsset(it), Charsets.UTF_8) }`. [versionName], [versionCode] and
 * [toolId] arrive from `BuildConfig`, which the Light plugin fills from `lighttool.toml`, so the lines on
 * screen cannot drift from the manifest the builder ships.
 *
 * `onScreenShow` fires on every `onResume` too — a volume press relaunches the tool — so the read is
 * guarded by [loaded] and a second show is a no-op. The guard sits in [load] rather than `onScreenShow`
 * because `onScreenShow` takes a `SimpleLightScreen`, which no JVM test can build.
 */
class AboutViewModel(
    private val readAsset: (String) -> String,
    versionName: String,
    versionCode: Int,
    toolId: String,
) : LightViewModel<Unit>() {
    private val _state = MutableStateFlow(AboutUiState(lines = identityLines(versionName, versionCode, toolId)))
    val state: StateFlow<AboutUiState> = _state.asStateFlow()

    private val _ticks = MutableSharedFlow<Int>(extraBufferCapacity = 16)

    /** One wheel detent: -1 toward the top of the phone (key 317), +1 toward the bottom (318). */
    val ticks: Flow<Int> = _ticks.asSharedFlow()

    private var loaded = false

    override fun onScreenShow(screen: SimpleLightScreen<Unit>) {
        super.onScreenShow(screen)
        viewModelScope.launch { load() }
    }

    /**
     * Read and parse the attribution — idempotent, so a relaunch's second `onScreenShow` returns at once.
     *
     * The read and the parse both run on [Dispatchers.Default]; the file is small, but it is still a
     * blocking asset read plus a Markdown parse on the frame the navigation lands on.
     *
     * A read failure cannot take the screen down: the identity lines are already in the state and stay
     * there under a quiet [ATTRIBUTION_UNAVAILABLE] line. Cancellation is not a failure — popping the
     * screen cancels `viewModelScope`, and swallowing that here would leave the coroutine looking alive.
     */
    internal suspend fun load() {
        if (loaded) return
        loaded = true
        val blocks = withContext(Dispatchers.Default) {
            val text = try {
                readAsset(ATTRIBUTION_PATH)
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                return@withContext null
            }
            Markdown.parse(text).map(::reflowed)
        }
        _state.value = if (blocks == null) {
            _state.value.copy(blocks = emptyList(), notice = ATTRIBUTION_UNAVAILABLE)
        } else {
            _state.value.copy(blocks = blocks, notice = null)
        }
    }

    /**
     * Wheel turns scroll the body; the press is consumed as a no-op because S16 has no action — an
     * unconsumed wheel event reaches LightOS, which relaunches the tool. Everything else (volume, camera)
     * stays unconsumed. See `WheelHandler`'s KDoc for the repo-wide convention.
     */
    fun handleKey(keyCode: Int): Boolean = when (WheelHandler.of(keyCode)) {
        WheelEvent.UP -> {
            _ticks.tryEmit(-1)
            true
        }
        WheelEvent.DOWN -> {
            _ticks.tryEmit(1)
            true
        }
        WheelEvent.PRESS -> true
        null -> false
    }

    /** Every key this screen swallows whatever the action — see [WheelHandler.consumes] for why the halves matter. */
    fun consumesKey(keyCode: Int): Boolean = WheelHandler.consumes(keyCode)

    override fun onKeyDown(keyCode: Int, event: KeyEvent): Boolean = handleKey(keyCode)

    override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean = consumesKey(keyCode)

    override fun onKeyMultiple(keyCode: Int, repeatCount: Int, event: KeyEvent): Boolean = consumesKey(keyCode)

    internal companion object {
        /** The generated attribution, as `readAsset` addresses it (assets root, like `compendium/index.json`). */
        const val ATTRIBUTION_PATH = "legal/ATTRIBUTION.md"

        /** The tool's own name (`lighttool.toml`'s label, ADR-0005) — the first identity line opens with it. */
        const val LABEL = "Grimoire"

        /** Plain text, never a link: zero permissions means there is no browser to open (ADR-0004). */
        const val REPOSITORY = "github.com/tyleryancey/light-grimoire"

        /**
         * The one line drawn if the bundled asset cannot be read at all. It points at the file rather than
         * paraphrasing it: the attribution is exact wording, and an approximation of it would be worse than
         * a pointer to the real thing.
         */
        const val ATTRIBUTION_UNAVAILABLE = "Attribution unavailable. It is in ATTRIBUTION.md in the repository."

        /**
         * S16's four plain lines, in the wireframe's order: version, tool id, the one compatibility claim
         * docs/LICENSING.md permits, and the repository as plain text.
         */
        fun identityLines(versionName: String, versionCode: Int, toolId: String): List<String> = listOf(
            "$LABEL $versionName ($versionCode)",
            toolId,
            "5E compatible",
            REPOSITORY,
        )

        /** A source line break inside one paragraph, rendered as the space that rejoins the sentence. */
        private val SOFT_BREAK = Span.Text(" ")

        /**
         * Rejoin the generated file's hard wrap. `pipeline/legal.py` wraps the attribution at its own
         * column width, which `Markdown.parse` keeps as [Span.LineBreak]s; honouring those on a ~38-character
         * screen would break every third line short. The reader (S10) needs real line breaks — the dragon
         * breath-weapon menus are written that way — so the reflow happens here rather than in the shared
         * renderer. Whitespace only: not one word of the attribution is altered, so LICENSING's "verbatim"
         * still holds.
         */
        fun reflowed(block: Block): Block = when (block) {
            is Block.Heading -> block.copy(spans = block.spans.map(::unwrapped))
            is Block.Para -> block.copy(spans = block.spans.map(::unwrapped))
            is Block.Bullet -> block.copy(spans = block.spans.map(::unwrapped))
            is Block.Numbered -> block.copy(spans = block.spans.map(::unwrapped))
            is Block.Field, is Block.Mono, is Block.Table -> block
        }

        private fun unwrapped(span: Span): Span = when (span) {
            is Span.Text -> span
            Span.LineBreak -> SOFT_BREAK
        }
    }
}
