package dev.tyler.grimoire

import java.io.File

/**
 * Golden fixtures generated by pipeline/ (see fixtures/ at the repo root). tool/build.gradle.kts hands the
 * directory to every Test task as -Dgrimoire.fixtures and declares it a task input, so a regenerated fixture
 * re-runs the replays. Reading in place avoids a copy that could drift and avoids srcDir(), which the SDK bans.
 */
object Fixtures {
    private val dir: File by lazy {
        val path = System.getProperty("grimoire.fixtures")
            ?: error("grimoire.fixtures system property is not set — run tests through Gradle (tool/build.gradle.kts sets it)")
        File(path).also { require(it.isDirectory) { "fixtures directory not found: $it" } }
    }

    fun text(relative: String): String = dir.resolve(relative).readText()
}
