package dev.tyler.grimoire

import dev.tyler.grimoire.compendium.CompendiumIndex
import dev.tyler.grimoire.compendium.CompendiumJson
import dev.tyler.grimoire.rules.ArmorStats
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File

/**
 * Golden fixtures generated by pipeline/ (see fixtures/ at the repo root). tool/build.gradle.kts hands the
 * directory to every Test task as -Dgrimoire.fixtures and declares it a task input, so a regenerated fixture
 * re-runs the replays. Reading in place avoids a copy that could drift and avoids srcDir(), which the SDK bans.
 * The bundled compendium (-Dgrimoire.compendium) is reachable the same way for the armor table.
 */
object Fixtures {
    private val dir: File by lazy { directory("grimoire.fixtures", "fixtures") }
    private val compendiumDir: File by lazy { directory("grimoire.compendium", "compendium") }

    private fun directory(property: String, what: String): File {
        val path = System.getProperty(property)
            ?: error("$property system property is not set — run tests through Gradle (tool/build.gradle.kts sets it)")
        return File(path).also { require(it.isDirectory) { "$what directory not found: $it" } }
    }

    fun text(relative: String): String = dir.resolve(relative).readText()

    /** A bundled compendium file (tool/src/main/assets/compendium) as text. */
    fun compendium(name: String): String = compendiumDir.resolve(name).readText()

    /** The same file as the exact bytes Light's builder bundles — what `readAsset` hands the importer. */
    fun compendiumBytes(name: String): ByteArray = compendiumDir.resolve(name).readBytes()

    /** index.json decoded strictly, the way AssetImporter reads it on device. */
    fun compendiumIndex(): CompendiumIndex =
        CompendiumJson.decodeFromString(CompendiumIndex.serializer(), compendium("index.json"))

    /**
     * The armor rows of equipment.json as the engine's [ArmorStats], keyed by equipment key — what the
     * compendium hands to Derive from M2 on. Like the fixture generator, only base/dexBonus/maxBonus are read.
     */
    fun armorTable(): Map<String, ArmorStats> =
        Json.parseToJsonElement(compendium("equipment.json")).jsonArray
            .map { it.jsonObject }
            .filter { it["armor"] != null && it["armor"] !is JsonNull }
            .associate { entry ->
                val armor = entry.getValue("armor").jsonObject
                entry.getValue("key").jsonPrimitive.content to ArmorStats(
                    base = armor.getValue("base").jsonPrimitive.int,
                    dexBonus = armor.getValue("dexBonus").jsonPrimitive.boolean,
                    maxBonus = armor["maxBonus"]?.takeUnless { it is JsonNull }?.jsonPrimitive?.int,
                )
            }

    /**
     * The JSON of a sample character under fixtures/characters/, by any of the three names the generated
     * fixtures use for it: the file name (`cleric-5-life.json`, derived.json), the stem (`cleric-5-life`,
     * events.json errors) or the character's id (`fixture-cleric-5-life`, events.json scenarios).
     */
    fun character(ref: String): String {
        val stem = ref.removeSuffix(".json").removePrefix("fixture-")
        return text("characters/$stem.json")
    }
}
